version: '3.8'

services:
  scraper:
    build: .
    container_name: web_scraper
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - SCRAPE_INTERVAL=600
    ports:
      - "8080:8080" # Expose health check endpoint
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: [ "python", "scraper.py" ]

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "python", "bot.py" ]
    depends_on:
      - scraper
